<?php

use Illuminate\Database\Seeder;

class RequisitesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('requisites')->insert(array(
			array('cid' => '107', 'prid' => '106', 'ORprid' => null, 'crid' => null),
			array('cid' => '111', 'prid' => '110', 'ORprid' => null, 'crid' => null),
			array('cid' => '115', 'prid' => null, 'ORprid' => null, 'crid' => '116'),
			array('cid' => '116', 'prid' => null, 'ORprid' => null, 'crid' => '115'),
			array('cid' => '48', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '56', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '72', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '73', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '74', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '80', 'prid' => null, 'ORprid' => null, 'crid' => '81'),
			array('cid' => '81', 'prid' => null, 'ORprid' => null, 'crid' => '80'),
			array('cid' => '98', 'prid' => '80', 'ORprid' => null, 'crid' => '101'),
			array('cid' => '99', 'prid' => '80', 'ORprid' => null, 'crid' => '101'),
			array('cid' => '100', 'prid' => '80', 'ORprid' => null, 'crid' => null),
			array('cid' => '101', 'prid' => null, 'ORprid' => null, 'crid' => '98'),
			array('cid' => '102', 'prid' => '98', 'ORprid' => '99', 'crid' => '103'),
			array('cid' => '103', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '104', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '105', 'prid' => null, 'ORprid' => null, 'crid' => '104'),
			array('cid' => '108', 'prid' => '80', 'ORprid' => '98', 'crid' => null),
			array('cid' => '109', 'prid' => null, 'ORprid' => null, 'crid' => '108'),
			array('cid' => '112', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '113', 'prid' => '115', 'ORprid' => '80', 'crid' => '114'),
			array('cid' => '114', 'prid' => null, 'ORprid' => null, 'crid' => '113'),
			array('cid' => '49', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '50', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '50', 'prid' => '55', 'ORprid' => null, 'crid' => null),
			array('cid' => '51', 'prid' => '56', 'ORprid' => null, 'crid' => null),
			array('cid' => '52', 'prid' => '56', 'ORprid' => null, 'crid' => null),
			array('cid' => '52', 'prid' => '51', 'ORprid' => null, 'crid' => null),
			array('cid' => '53', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '53', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '54', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '57', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '58', 'prid' => '104', 'ORprid' => null, 'crid' => '57'),
			array('cid' => '59', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '59', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '61', 'prid' => '60', 'ORprid' => null, 'crid' => null),
			array('cid' => '62', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '63', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '63', 'prid' => '53', 'ORprid' => null, 'crid' => null),
			array('cid' => '66', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '67', 'prid' => '63', 'ORprid' => '69', 'crid' => null),
			array('cid' => '68', 'prid' => null, 'ORprid' => null, 'crid' => '65'),
			array('cid' => '70', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '71', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '71', 'prid' => '47', 'ORprid' => '43', 'crid' => null),
			array('cid' => '75', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '76', 'prid' => '75', 'ORprid' => null, 'crid' => null),
			array('cid' => '78', 'prid' => '77', 'ORprid' => null, 'crid' => null),
			array('cid' => '79', 'prid' => '62', 'ORprid' => null, 'crid' => null),
			array('cid' => '82', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '83', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '85', 'prid' => '84', 'ORprid' => null, 'crid' => null),
			array('cid' => '86', 'prid' => '64', 'ORprid' => null, 'crid' => null),
			array('cid' => '87', 'prid' => '71', 'ORprid' => null, 'crid' => null),
			array('cid' => '89', 'prid' => '88', 'ORprid' => null, 'crid' => null),
			array('cid' => '89', 'prid' => '78', 'ORprid' => null, 'crid' => null),
			array('cid' => '90', 'prid' => '75', 'ORprid' => '77', 'crid' => null),
			array('cid' => '90', 'prid' => '62', 'ORprid' => null, 'crid' => null),
			array('cid' => '91', 'prid' => '62', 'ORprid' => null, 'crid' => null),
			array('cid' => '91', 'prid' => '43', 'ORprid' => null, 'crid' => null),
			array('cid' => '92', 'prid' => '78', 'ORprid' => null, 'crid' => null),
			array('cid' => '92', 'prid' => '89', 'ORprid' => null, 'crid' => null),
			array('cid' => '94', 'prid' => '93', 'ORprid' => null, 'crid' => null),
			array('cid' => '95', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '96', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '97', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '41', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '43', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '44', 'prid' => '43', 'ORprid' => '47', 'crid' => null),
			array('cid' => '44', 'prid' => '42', 'ORprid' => null, 'crid' => null),
			array('cid' => '46', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '47', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '1', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '2', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '3', 'prid' => '102', 'ORprid' => null, 'crid' => null),
			array('cid' => '3', 'prid' => '62', 'ORprid' => null, 'crid' => null),
			array('cid' => '3', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '4', 'prid' => '3', 'ORprid' => null, 'crid' => null),
			array('cid' => '5', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '6', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '8', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '8', 'prid' => '13', 'ORprid' => null, 'crid' => null),
			array('cid' => '9', 'prid' => '104', 'ORprid' => null, 'crid' => null),
			array('cid' => '9', 'prid' => '43', 'ORprid' => '47', 'crid' => null),
			array('cid' => '10', 'prid' => '98', 'ORprid' => null, 'crid' => null),
			array('cid' => '10', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '10', 'prid' => '47', 'ORprid' => null, 'crid' => null),
			array('cid' => '10', 'prid' => '44', 'ORprid' => null, 'crid' => null),
			array('cid' => '11', 'prid' => '45', 'ORprid' => null, 'crid' => null),
			array('cid' => '12', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '13', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '13', 'prid' => '44', 'ORprid' => null, 'crid' => null),
			array('cid' => '13', 'prid' => '47', 'ORprid' => null, 'crid' => null),
			array('cid' => '14', 'prid' => '13', 'ORprid' => null, 'crid' => null),
			array('cid' => '15', 'prid' => '108', 'ORprid' => null, 'crid' => null),
			array('cid' => '15', 'prid' => '44', 'ORprid' => null, 'crid' => null),
			array('cid' => '19', 'prid' => '18', 'ORprid' => null, 'crid' => null),
			array('cid' => '20', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '20', 'prid' => '11', 'ORprid' => null, 'crid' => null),
			array('cid' => '21', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '22', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '22', 'prid' => '13', 'ORprid' => null, 'crid' => null),
			array('cid' => '22', 'prid' => '1', 'ORprid' => null, 'crid' => null),
			array('cid' => '23', 'prid' => '22', 'ORprid' => null, 'crid' => null),
			array('cid' => '24', 'prid' => '10', 'ORprid' => null, 'crid' => null),
			array('cid' => '24', 'prid' => '45', 'ORprid' => null, 'crid' => null),
			array('cid' => '25', 'prid' => '44', 'ORprid' => null, 'crid' => null),
			array('cid' => '26', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '27', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '28', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '29', 'prid' => '12', 'ORprid' => null, 'crid' => null),
			array('cid' => '30', 'prid' => '16', 'ORprid' => '7', 'crid' => null),
			array('cid' => '31', 'prid' => '22', 'ORprid' => null, 'crid' => null),
			array('cid' => '32', 'prid' => '14', 'ORprid' => null, 'crid' => null),
			array('cid' => '33', 'prid' => '16', 'ORprid' => null, 'crid' => null),
			array('cid' => '34', 'prid' => '17', 'ORprid' => null, 'crid' => null),
			array('cid' => '35', 'prid' => null, 'ORprid' => null, 'crid' => null),
			array('cid' => '36', 'prid' => '12', 'ORprid' => null, 'crid' => null),
			array('cid' => '37', 'prid' => '19', 'ORprid' => null, 'crid' => null),
			array('cid' => '38', 'prid' => '20', 'ORprid' => null, 'crid' => null),
			array('cid' => '39', 'prid' => '22', 'ORprid' => null, 'crid' => null),
			array('cid' => '40', 'prid' => null, 'ORprid' => null, 'crid' => null),
		));
    }
}
